#!/bin/bash

# exit loop if user wants to exit early with Control+C 
trap "exit" INT

filesystem=$1

if [ $4 = "DSCAlexxor" ]; then
    const=-0.25
    step=-0.05
    stopNum=-0.35
elif [ $4 = "Spectra4000" ]; then
    const=-0.02
    step=-0.01
    stopNum=-0.05
elif [ $4 = "YaleStandard" ]; then
    const=-0.1
    step=-0.05
    stopNum=-0.25
elif [ $4 = "Bosch3000" ]; then
    const=-0.01
    step=-0.1
    stopNum=-0.21
elif [ $4 = "IQPanel" ]; then
    const=-0.01
    step=-0.02
    stopNum=-0.21
else
    const=-0.0
    step=-0.1
    stopNum=-0.2
fi

calcStopLoop=$(echo "$const" |awk '{print "'$stopNum'"-"'$const'"}');
stopLoopTotal=$(echo "$const" |awk '{print "'$calcStopLoop'"/"'$step'"}');

for fs in $filesystem
do
# Loop AddConst offset -0.25 to -0.9 as defined above

    for((c=0; c<=stopLoopTotal; c++))
     do 
      Number=$(echo "$const" |awk '{print "'$const'"+"'$step'"*"'$c'"}');
      echo "Processing loop - AddConst offset - [Hit CTRL+Z to stop]"

      # Need to have a timeout, as each flowgraph will not stop otherwise
      # format: timeout 60s python /home/user/GnuRadioFiles/DSC_FileInput_To_BinarySlice_xyz.py "$Number" $3 -e
      timeout 60s python $2 "$Number" $3 -e
    done
done
